#NumPy basic

In [ ]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
array1=np.array([10,20,30])

In [ ]:
array1

array([10, 20, 30])

In [ ]:
array2=np.array([5,-7.4,'a',7.2])

In [ ]:
array2  # unicode-32 datatype means string

array(['5', '-7.4', 'a', '7.2'], dtype='<U32')

In [ ]:
array3=np.array([[2.4,3],[4.91,7],[0,-1]])

In [ ]:
array3

array([[ 2.4 ,  3.  ],
       [ 4.91,  7.  ],
       [ 0.  , -1.  ]])

In [ ]:
array1.ndim

1

In [ ]:
array3.ndim # dimensional

2

In [ ]:
array1.shape

(3,)

In [ ]:
array2.shape

(4,)

In [ ]:
array3.shape # row and column

(3, 2)

In [ ]:
array1.size # total elements

3

In [ ]:
array3.size

6

In [ ]:
array1.dtype # for datatype

dtype('int64')

In [ ]:
array3.dtype

dtype('float64')

In [ ]:
array1.itemsize # memory allocated to interger64 datatype

8

In [ ]:
array3.itemsize  #memory allocated to float

8

In [ ]:
array2.itemsize # memory allocated to string data type

128

In [ ]:
array4=np.array([[1,2],[3,4]],dtype=float) # creating numpy array in another way - see the elements and its datatype

In [ ]:
array4

array([[1., 2.],
       [3., 4.]])

In [ ]:
array5=np.zeros((3,4)) # array with zero element by default dtype is float

In [ ]:
array5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array6=np.ones((3,4)) # array with one value by default dtype is float

In [ ]:
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
array7=np.arange(6) # create a numpy array with using this arange fn - sequence manner

In [ ]:
array7

array([0, 1, 2, 3, 4, 5])

In [ ]:
array8=np.arange(-2,24,4) # starting is -2 and increment by 4 till 24 element

In [ ]:
array8

array([-2,  2,  6, 10, 14, 18, 22])

# Indexing and slicing

In [ ]:
array8

array([-2,  2,  6, 10, 14, 18, 22])

In [ ]:
array8[3:5] # end is exclude

array([10, 14])

In [ ]:
array8[::-1] # reverse the array

array([22, 18, 14, 10,  6,  2, -2])

In [ ]:
array9=np.array([[-7,0,10,20], # create numpy array for slicing - 3R and 4C
                 [-5,1,40,200],
                 [-1,1,4,30]])

In [ ]:
array9[1:3,0:2]  # first one is for row and second one is for column

array([[-5,  1],
       [-1,  1]])

In [ ]:
array9[:,2] # row is all and collumn is second one

array([10, 40,  4])

# Operations on array

In [ ]:
array1=np.array([[3,6],[4,2]])

In [ ]:
array2=np.array([[10,20],[15,12]])

In [ ]:
array1+array2 # addition of two matrics

array([[13, 26],
       [19, 14]])

In [ ]:
array1-array2 # subtraction

array([[ -7, -14],
       [-11, -10]])

In [ ]:
array1*array2

array([[ 30, 120],
       [ 60,  24]])

In [ ]:
array1**3 # Exponentiation

array([[ 27, 216],
       [ 64,   8]])

In [ ]:
array2/array1

array([[3.33333333, 3.33333333],
       [3.75      , 6.        ]])

In [ ]:
array2%array1

array([[1, 2],
       [3, 0]])

In [ ]:
array3=np.array([[10,-7,0,20],[-5,1,200,40],[30,1,-1,4]]) # for finding matrix

In [ ]:
array3

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [ ]:
array3.transpose()

array([[ 10,  -5,  30],
       [ -7,   1,   1],
       [  0, 200,  -1],
       [ 20,  40,   4]])

In [ ]:
array4=np.array([1,0,2,-3,6,8,4,7])

In [ ]:
array4.sort() # sorting

In [ ]:
array4

array([-3,  0,  1,  2,  4,  6,  7,  8])

In [ ]:
array4=np.array([[10,-7,0,20],[-5,1,200,40],[30,1,-1,4]])

In [ ]:
array4

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [ ]:
array4.sort() # by defauly row wise sorting axix =1 value- ascending order

In [ ]:
array4

array([[ -7,   0,  10,  20],
       [ -5,   1,  40, 200],
       [ -1,   1,   4,  30]])

In [ ]:
array5=np.array([[10,-7,0,20],[-5,1,200,40],[30,1,-1,4]])
array5

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [ ]:
array5.sort(axis=0)

In [ ]:
array5

array([[ -5,  -7,  -1,   4],
       [ 10,   1,   0,  20],
       [ 30,   1, 200,  40]])

In [ ]:
#concatenating array
array1=np.array([[10,20],[-30,40]])
array2=np.zeros((2,3),dtype=array1.dtype)

In [ ]:
array1

array([[ 10,  20],
       [-30,  40]])

In [ ]:
array2

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
array1.shape


(2, 2)

In [ ]:
array2.shape

(2, 3)

In [ ]:
np.concatenate((array1,array2),axis=1) # by default row wise concatenate if any mismatch occur then the result will be error
# just check with axis =0 then the error will come

array([[ 10,  20,   0,   0,   0],
       [-30,  40,   0,   0,   0]])

In [ ]:
# reshaping arrays
array3=np.arange(10,22)
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [ ]:
array3.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
array3.reshape(2,6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [ ]:
# Splitting array
array4=np.array([[10,-7,0,20],[-5,1,200,40],[30,1,-1,4],[1,2,0,4],[0,1,0,2]])
array4

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4],
       [  1,   2,   0,   4],
       [  0,   1,   0,   2]])

In [ ]:
first,second,third=np.split(array4,[1,3]) # by default it will take the row indices

In [ ]:
first # only it will take the first row

array([[10, -7,  0, 20]])

In [ ]:
second # it will take after the first row and upto the third row

array([[ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [ ]:
third # remaining rows are printed here

array([[1, 2, 0, 4],
       [0, 1, 0, 2]])

In [ ]:
array4

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4],
       [  1,   2,   0,   4],
       [  0,   1,   0,   2]])

In [ ]:
firstc,secondc,thirdc=np.split(array4,[1,2],axis=1) # column wise split - first column only it will take

In [ ]:
firstc

array([[10],
       [-5],
       [30],
       [ 1],
       [ 0]])

In [ ]:
 #it will print only the second column
secondc

array([[-7],
       [ 1],
       [ 1],
       [ 2],
       [ 1]])

In [ ]:
thirdc # it will take the remaning column

array([[  0,  20],
       [200,  40],
       [ -1,   4],
       [  0,   4],
       [  0,   2]])

In [ ]:
firsthalf,secondhalf=np.split(array4,2,axis=1) # it will split the matrix into two equal column

In [ ]:
firsthalf

array([[10, -7],
       [-5,  1],
       [30,  1],
       [ 1,  2],
       [ 0,  1]])

In [ ]:
secondhalf

array([[  0,  20],
       [200,  40],
       [ -1,   4],
       [  0,   4],
       [  0,   2]])

# Statistical operations on array

In [ ]:
# letus construct two array
arrayA=np.array([1,0,2,-3,6,8,4,7])
arrayB=np.array([[3,6],[4,2]])

In [ ]:
arrayA.max()


8

In [ ]:
arrayB.max()

6

In [ ]:
arrayB

array([[3, 6],
       [4, 2]])

In [ ]:
arrayB.max(axis=1) # column wise max

array([6, 4])

In [ ]:
arrayB.max(axis=0) # row wise max element

array([4, 6])

In [ ]:
arrayB.min(axis=0) # row wise minimum element

array([3, 2])

In [ ]:
arrayB.min() # minimum element from entire array

2

In [ ]:
arrayA.sum() # sum of all elements

25

In [ ]:
arrayB.sum(axis=1) # column wise sum

array([9, 6])

In [ ]:
arrayA.mean()

3.125

In [ ]:
arrayB.mean(axis=0)

array([3.5, 4. ])

In [ ]:
arrayA.std()

3.550968177835448

In [ ]:
arrayB.std(axis=1)

array([1.5, 1. ])

#Loading Array from Files

In [ ]:
# loadtxt() and genfromtxt() functions are used to load the array frm files
#load into colab and execute it
studentdata=np.loadtxt('data.txt',skiprows=1,delimiter=',',dtype=int)

In [ ]:
studentdata

array([[ 1, 36, 18, 57],
       [ 2, 22, 23, 45],
       [ 3, 43, 51, 37],
       [ 4, 41, 40, 60],
       [ 5, 13, 18, 37]])

In [ ]:
# extract the array as row wise - by default unpack=False
stud1,stud2,stud3,stud4,stud5=np.loadtxt('data.txt',skiprows=1,delimiter=',',dtype=int)

In [ ]:
stud1

array([ 1, 36, 18, 57])

In [ ]:
stud5

array([ 5, 13, 18, 37])

In [ ]:
rollno,mks1,mks2,mks3=np.loadtxt('data.txt',skiprows=1,delimiter=',',unpack=True,dtype=int)

In [ ]:
rollno

array([1, 2, 3, 4, 5])

In [ ]:
mks2

array([18, 23, 51, 40, 18])

In [ ]:
# load the data using genfromtxt method .It is very useful for handlling missing value in the file
# by default the datatype is float
dataarray=np.genfromtxt('data_missing.txt',skip_header=1,delimiter=',')

In [ ]:
dataarray

array([[ 1., nan, 18., 57.],
       [ 2., 22., 23., 45.],
       [ 3., 43., 51., 37.],
       [ 4., nan, 40., 60.],
       [ 5., 13., 18., nan]])

In [ ]:
# going to replace the missing values
dataarray=np.genfromtxt('data_missing.txt',skip_header=1,delimiter=',',filling_values=-99,dtype=int)

In [ ]:
dataarray

array([[  1, -99,  18,  57],
       [  2,  22,  23,  45],
       [  3,  43,  51,  37],
       [  4, -99,  40,  60],
       [  5,  13,  18, -99]])

In [ ]:
studentdata

array([[ 1, 36, 18, 57],
       [ 2, 22, 23, 45],
       [ 3, 43, 51, 37],
       [ 4, 41, 40, 60],
       [ 5, 13, 18, 37]])

In [ ]:
# Saving Numpy array in files on Disk
np.savetxt('testout.txt',studentdata,delimiter=',',fmt='%i') # fmt is format in which datas are stored
#by default it is float format

In [ ]:
np.savetxt('testout_1.txt',dataarray,delimiter=',',fmt='%i') # save in the google colab

#Pandas Intro
# Creating of series from scalar values

In [ ]:
import pandas as pd
pd.__version__

'1.3.5'

In [ ]:
# series is a one dimensional array containing a sequence of values of any type
series1=pd.Series([10,20,30])

In [ ]:
series1

0    10
1    20
2    30
dtype: int64

In [ ]:
series2=pd.Series(['kavi','kumar','ram'],index=[3,5,1])

In [ ]:
series2

3     kavi
5    kumar
1      ram
dtype: object

In [ ]:
series2=pd.Series([2,3,4],index=["Feb","March","A"])


In [ ]:
series2

Feb      2
March    3
A        4
dtype: int64

In [ ]:
# creating of series from numpy arrays
import numpy as np
import pandas as pd
array1=np.array([1,2,3,4])
series3=pd.Series(array1)
print(series3)

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
series4=pd.Series(array1,index=['jan','feb','mar','apr'])

In [ ]:
print(series4) # note the length of the array and index should be same . Otherwise error will come

jan    1
feb    2
mar    3
apr    4
dtype: int64


In [ ]:
#creation of series from dictionary
dict1={'India':'NewDelhi','Uk':'London','japan':'tokyo'}

In [ ]:
print(dict1)

{'India': 'NewDelhi', 'Uk': 'London', 'japan': 'tokyo'}


In [ ]:
series8=pd.Series(dict1)
series8

India    NewDelhi
Uk         London
japan       tokyo
dtype: object

In [ ]:
#accessing elements of a series
#indexing
seriesNum=pd.Series([10,20,30])
seriesNum[2]

30

In [ ]:
seriesMnths=pd.Series([2,3,4],index=['Feb','Mar','Apr'])

In [ ]:
seriesMnths["Mar"]

3

In [ ]:
seriesCapCntry=pd.Series(['NewDelhi','Washington','London','Paris'],index=['India','USA','UK','France'])

In [ ]:
seriesCapCntry['India']

'NewDelhi'

In [ ]:
seriesCapCntry[1]

'Washington'

In [ ]:
seriesCapCntry[[2,3]] # row match first and column match second - start from Zero

UK        London
France     Paris
dtype: object

In [ ]:
seriesCapCntry[['UK','USA']]

UK         London
USA    Washington
dtype: object

In [ ]:
seriesCapCntry.index=[10,20,30,40]
seriesCapCntry

10      NewDelhi
20    Washington
30        London
40         Paris
dtype: object

In [ ]:
#slicing
seriesCapCntry[1:3] # exclude the value of 3

20    Washington
30        London
dtype: object

In [ ]:
seriesCapCntry

10      NewDelhi
20    Washington
30        London
40         Paris
dtype: object

In [ ]:
seriesCapCntry=pd.Series(['NewDelhi','Washington','London','Paris'],index=['India','USA','UK','France'])

In [ ]:
seriesCapCntry['USA':'France']

USA       Washington
UK            London
France         Paris
dtype: object

In [ ]:
seriesCapCntry[::-1] # reverse order

France         Paris
UK            London
USA       Washington
India       NewDelhi
dtype: object

In [ ]:
# Slicing for series of pandas
seriesAlpha=pd.Series(np.arange(10,16,1),index=['a','b','c','d','e','f'])

In [ ]:
seriesAlpha

a    10
b    11
c    12
d    13
e    14
f    15
dtype: int64

In [ ]:
seriesAlpha[1:3]=50

In [ ]:
seriesAlpha

a    10
b    50
c    50
d    13
e    14
f    15
dtype: int64

In [ ]:
seriesAlpha['c':'e']=500
seriesAlpha

a     10
b     50
c    500
d    500
e    500
f     15
dtype: int64

# Attributes of a Pandas Series

In [ ]:
seriesCapCntry

India       NewDelhi
USA       Washington
UK            London
France         Paris
dtype: object

In [ ]:
# assign a name to the series - See the bottom of the output Name:Capitals
seriesCapCntry.name='Capitals'
print(seriesCapCntry)

India       NewDelhi
USA       Washington
UK            London
France         Paris
Name: Capitals, dtype: object


In [ ]:
#assign a name to the index of the sereis
seriesCapCntry.index.name='Countries'
print(seriesCapCntry)

Countries
India       NewDelhi
USA       Washington
UK            London
France         Paris
Name: Capitals, dtype: object


In [ ]:
# print the list of values in the series
print(seriesCapCntry.values)

['NewDelhi' 'Washington' 'London' 'Paris']


In [ ]:
#print the total valeus in the series
print(seriesCapCntry.size)

4


In [ ]:
#print true if the series is empty and false otherwise
seriesCapCntry.empty

False

In [ ]:
seriesEmpt=pd.Series()
seriesEmpt.empty

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """Entry point for launching an IPython kernel.


True

#Methods of sereis in pandas

In [ ]:
seriesTenTwenty=pd.Series(np.arange(10,20,1))

In [ ]:
print(seriesTenTwenty)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [ ]:
seriesTenTwenty.head(2)

0    10
1    11
dtype: int64

In [ ]:
seriesTenTwenty.head() # by default it will display 5 values

0    10
1    11
2    12
3    13
4    14
dtype: int64

In [ ]:
seriesTenTwenty.count() # total elements


10

In [ ]:
seriesTenTwenty.tail(2) # by default it will display 5 values

8    18
9    19
dtype: int64

In [ ]:
# Mathematical operations on series
seriesA=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [ ]:
seriesA

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
seriesB=pd.Series([10,20,-10,-50,100],index=['z','y','a','c','e'])

In [ ]:
seriesB

z     10
y     20
a    -10
c    -50
e    100
dtype: int64

In [ ]:
#addition of two series , Arrange in ascending order then we can add the series
# if any one element is missing then the output is NaN -> Check the order
seriesA+seriesB

a     -9.0
b      NaN
c    -47.0
d      NaN
e    105.0
y      NaN
z      NaN
dtype: float64

In [ ]:
seriesA.add(seriesB,fill_value=0) # It will add if anyone value is present
# we can avoid nan in this method

a     -9.0
b      2.0
c    -47.0
d      4.0
e    105.0
y     20.0
z     10.0
dtype: float64

In [ ]:
#subtraction
seriesA - seriesB

a    11.0
b     NaN
c    53.0
d     NaN
e   -95.0
y     NaN
z     NaN
dtype: float64

In [ ]:
seriesA.sub(seriesB,fill_value=1000) # It will fill 1000 in NAN position

a     11.0
b   -998.0
c     53.0
d   -996.0
e    -95.0
y    980.0
z    990.0
dtype: float64

In [ ]:
#Multiplicaiton of two series
seriesA*seriesB

a    -10.0
b      NaN
c   -150.0
d      NaN
e    500.0
y      NaN
z      NaN
dtype: float64

In [ ]:
# fill missinng value with zero
seriesA.mul(seriesB,fill_value=0)

a    -10.0
b      0.0
c   -150.0
d      0.0
e    500.0
y      0.0
z      0.0
dtype: float64

In [ ]:
#division of two series
seriesA/seriesB

a   -0.10
b     NaN
c   -0.06
d     NaN
e    0.05
y     NaN
z     NaN
dtype: float64

In [ ]:
#fill missing value with zero
seriesA.div(seriesB,fill_value=0)

a   -0.10
b     inf
c   -0.06
d     inf
e    0.05
y    0.00
z    0.00
dtype: float64

#DataFrame

In [ ]:
#creating empty dataframe
dFrameEmt=pd.DataFrame()
dFrameEmt

Empty DataFrame
Columns: []
Index: []

In [ ]:
#creation of dataframe from numpy ndarrays
array1=np.array([10,20,30])
array2=np.array([100,200,300])
array3=np.array([-10,-20,-30,-40])


In [ ]:
dFrame4=pd.DataFrame(array1)
dFrame4

0
0  10
1  20
2  30

In [ ]:
dFrame5=pd.DataFrame([array1,array3,array2],columns=['A','B','C','D'])
dFrame5

A    B    C     D
0   10   20   30   NaN
1  -10  -20  -30 -40.0
2  100  200  300   NaN

In [ ]:
#creation of dataframe from list of dictionaries
listDic=[{'a':10,'b':20},{'a':5,'b':10,'c':20}]

In [ ]:
dFrameListDic=pd.DataFrame(listDic)
dFrameListDic

a   b     c
0  10  20   NaN
1   5  10  20.0

In [ ]:
# creation of dataframe from dictionary of lists
dictForest={'state':['Assam','Delhi','Kerela'],'GArea':[78438,1483,38852],'VDF':[2797,6.72,1663]}

In [ ]:
dFrameForest=pd.DataFrame(dictForest)
dFrameForest


state  GArea      VDF
0   Assam  78438  2797.00
1   Delhi   1483     6.72
2  Kerela  38852  1663.00

In [ ]:
# changing column in the dataframe - change order of key value in the dictionary

dFrameForest1=pd.DataFrame(dictForest,columns=['state','VDF','GArea'])
dFrameForest1

state      VDF  GArea
0   Assam  2797.00  78438
1   Delhi     6.72   1483
2  Kerela  1663.00  38852

In [ ]:
#Creation of dataframe from series
seriesA=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [ ]:
seriesB=pd.Series([1000,2000,-1000,-5000,1000],index=['a','b','c','d','e'])

In [ ]:
seriesC=pd.Series([10,20,-10,-50,100],index=['z','y','a','c','e'])

In [ ]:
dFrame6=pd.DataFrame(seriesA)
dFrame6

0
a  1
b  2
c  3
d  4
e  5

In [ ]:
dFrame7=pd.DataFrame([seriesA,seriesB])
dFrame7

a     b     c     d     e
0     1     2     3     4     5
1  1000  2000 -1000 -5000  1000

In [ ]:
dFrame8=pd.DataFrame([seriesA,seriesC])
dFrame8


a    b     c    d      e     z     y
0   1.0  2.0   3.0  4.0    5.0   NaN   NaN
1 -10.0  NaN -50.0  NaN  100.0  10.0  20.0

In [ ]:
#creation of dataframe from dictionary of series
# studens mark statement
ResultSheet={
    'Arun':pd.Series([90,91,97],
                     index=['Maths','Science','Hindi']),
             'Ram':pd.Series([92,81,96],
                             index=['Maths','Science','Hindi']),
             'sam':pd.Series([89,91,88],
                             index=['Maths','Science','Hindi']),
             'Mallika':pd.Series([94,95,99],
             index=['Maths','Science','Hindi'])
}

In [ ]:
ResultDF=pd.DataFrame(ResultSheet)
ResultDF

Arun  Ram  sam  Mallika
Maths      90   92   89       94
Science    91   81   91       95
Hindi      97   96   88       99

In [ ]:
type(ResultDF.Arun) # series

pandas.core.series.Series

In [ ]:
#another series example
dictForUnion={'Series1':
              pd.Series([1,2,3,4,5],
                        index=['a','b','c','d','e']),
              'Series2':
              pd.Series([10,20,-10,-50,100],
                        index=['z','y','a','c','e']),
              'Series3':
              pd.Series([10,20,-10,-50,100],index=['z','y','a','c','e'])
              }

In [ ]:
dFrameUnion=pd.DataFrame(dictForUnion)

In [ ]:
dFrameUnion

Series1  Series2  Series3
a      1.0    -10.0    -10.0
b      2.0      NaN      NaN
c      3.0    -50.0    -50.0
d      4.0      NaN      NaN
e      5.0    100.0    100.0
y      NaN     20.0     20.0
z      NaN     10.0     10.0

#Operations on rows and columns in DataFrame

In [ ]:
# Adding new Column to a DataFrame , Check the previous dataframe we can add this column
ResultDF['Preeti']=[89,78,76]
ResultDF

Arun  Ram  sam  Mallika  Preeti
Maths      90   92   89       94      89
Science    91   81   91       95      78
Hindi      97   96   88       99      76

In [ ]:
ResultDF['Ram']=[99,98,78] # It will change the entire column of arum
ResultDF

Arun  Ram  sam  Mallika  Preeti
Maths      90   99   89       94      89
Science    91   98   91       95      78
Hindi      97   78   88       99      76

In [ ]:
ResultDF['Arun']=90 # It will update the column
ResultDF

Arun  Ram  sam  Mallika  Preeti
Maths      90   99   89       94      89
Science    90   98   91       95      78
Hindi      90   78   88       99      76

In [ ]:
# using loc method we can add the Row
ResultDF.loc['English']=[85,86,83,80,90]
ResultDF

Arun  Ram  sam  Mallika  Preeti
Maths      90   99   89       94      89
Science    90   98   91       95      78
Hindi      90   78   88       99      76
English    85   86   83       80      90

In [ ]:
ResultDF.loc['English']=[95,96,93,90,95] # It will update the Result
ResultDF

Arun  Ram  sam  Mallika  Preeti
Maths      90   99   89       94      89
Science    90   98   91       95      78
Hindi      90   78   88       99      76
English    95   96   93       90      95

In [ ]:
#using loc to change the values
ResultDF.loc['Maths']=0
ResultDF

Arun  Ram  sam  Mallika  Preeti
Maths       0    0    0        0       0
Science    90   98   91       95      78
Hindi      90   78   88       99      76
English    95   96   93       90      95

In [ ]:
# to set all the valeus to Zero
ResultDF[:]=0
ResultDF

Arun  Ram  sam  Mallika  Preeti
Maths       0    0    0        0       0
Science     0    0    0        0       0
Hindi       0    0    0        0       0
English     0    0    0        0       0

In [ ]:
ResultSheet={
    'Arun':pd.Series([90,91,97],
                     index=['Maths','Science','Hindi']),
             'Ram':pd.Series([92,81,96],
                             index=['Maths','Science','Hindi']),
             'sam':pd.Series([89,91,88],
                             index=['Maths','Science','Hindi']),
             'Mallika':pd.Series([94,95,99],
             index=['Maths','Science','Hindi'])
}

In [ ]:
ResultDF=pd.DataFrame(ResultSheet)
ResultDF

Arun  Ram  sam  Mallika
Maths      90   92   89       94
Science    91   81   91       95
Hindi      97   96   88       99

In [ ]:
# deletingn row or column for dataframe
ResultDF=ResultDF.drop('Science',axis=0)

In [ ]:
ResultDF

Arun  Mallika
Maths    90       94
Hindi    97       99

In [ ]:
ResultDF

In [ ]:
ResultDF=ResultDF.drop(['Mallika'],axis=1)
ResultDF

Arun
Maths    90
Hindi    97

In [ ]:
# Renaming Row lables of a DataFrame
ResultSheet={
    'Arun':pd.Series([90,91,97],
                     index=['Maths','Science','Hindi']),
             'Ram':pd.Series([92,81,96],
                             index=['Maths','Science','Hindi']),
             'sam':pd.Series([89,91,88],
                             index=['Maths','Science','Hindi']),
             'Mallika':pd.Series([94,95,99],
             index=['Maths','Science','Hindi'])
}
ResultDF=pd.DataFrame(ResultSheet)
ResultDF


Arun  Ram  sam  Mallika
Maths      90   92   89       94
Science    91   81   91       95
Hindi      97   96   88       99

In [ ]:
ResultDF=ResultDF.rename({'Maths':'Sub1','Science':'Sub2','Hindi':'Sub3'},axis='index')

In [ ]:
ResultDF

Arun  Ram  sam  Mallika
Sub1    90   92   89       94
Sub2    91   81   91       95
Sub3    97   96   88       99

In [ ]:
# Renaming Column Labels of a DataFrame
ResultDF=ResultDF.rename({'Arun':'Student1','Ram':'Student2','sam':'Student3','Mallika':'Student4'},axis=1)
# we can give axis =1 or axis='columns'

In [ ]:
ResultDF

Student1  Student2  Student3  Student4
Sub1        90        92        89        94
Sub2        91        81        91        95
Sub3        97        96        88        99

In [ ]:
#Accessing dataframe elements through indexing
#Label Based Indexing


In [ ]:
ResultSheet={
    'Arun':pd.Series([90,91,97],
                     index=['Maths','Science','Hindi']),
             'Ram':pd.Series([92,81,96],
                             index=['Maths','Science','Hindi']),
             'sam':pd.Series([89,91,88],
                             index=['Maths','Science','Hindi']),
             'Mallika':pd.Series([94,95,99],
             index=['Maths','Science','Hindi'])
}
ResultDF=pd.DataFrame(ResultSheet)
ResultDF

Arun  Ram  sam  Mallika
Maths      90   92   89       94
Science    91   81   91       95
Hindi      97   96   88       99

In [ ]:
ResultDF.loc['Science']

Arun       91
Ram        81
sam        91
Mallika    95
Name: Science, dtype: int64

In [ ]:
# another example
dFrame10Mutiples=pd.DataFrame([10,20,30,40,50])

In [ ]:
dFrame10Mutiples.loc[2] # 0 axis and another one is value

0    30
Name: 2, dtype: int64

In [ ]:
# Column extraction
ResultDF.loc[:,'Arun']

Maths      90
Science    91
Hindi      97
Name: Arun, dtype: int64

In [ ]:
# another way
print(ResultDF['Arun'])

Maths      90
Science    91
Hindi      97
Name: Arun, dtype: int64


In [ ]:
ResultDF.loc[['Science','Hindi']]

Arun  Ram  sam  Mallika
Science    91   81   91       95
Hindi      97   96   88       99

In [ ]:
#Boolean Indexing - return true or false
ResultDF.loc['Maths']>90

Arun       False
Ram         True
sam        False
Mallika     True
Name: Maths, dtype: bool

In [ ]:
ResultDF.loc[:,'Arun']>90

Maths      False
Science     True
Hindi       True
Name: Arun, dtype: bool

In [ ]:
# Accessing DataFrame elements through Slicing
ResultDF

Arun  Ram  sam  Mallika
Maths      90   92   89       94
Science    91   81   91       95
Hindi      97   96   88       99

In [ ]:
ResultDF.loc['Maths':'Science']

Maths      90
Science    91
Name: Arun, dtype: int64

In [ ]:
ResultDF.loc['Maths':'Science','Arun']

Maths      90
Science    91
Name: Arun, dtype: int64

In [ ]:
ResultDF

Arun  Ram  sam  Mallika
Maths      90   92   89       94
Science    91   81   91       95
Hindi      97   96   88       99

In [ ]:
ResultDF.loc['Maths':'Science','Arun':'Mallika']

Arun  Ram  sam  Mallika
Maths      90   92   89       94
Science    91   81   91       95

In [ ]:
ResultDF.loc['Maths':'Science',['Arun','sam']]

Arun  sam
Maths      90   89
Science    91   91

In [ ]:
# Filtering Rows in DataFrame
ResultDF

Arun  Ram  sam  Mallika
Maths      90   92   89       94
Science    91   81   91       95
Hindi      97   96   88       99

In [ ]:
ResultDF.loc[[True,False,True]] # second row will be omitted

Arun  Ram  sam  Mallika
Maths    90   92   89       94
Hindi    97   96   88       99

# Joining,Merging and Concatenation of DataFrames

In [ ]:
from tables.table import Column
# Joining
dFrame1=pd.DataFrame([[1,2,3],[4,5],[6]],columns=['C1','C2','C3'],index=['R1','R2','R3'])

In [ ]:
dFrame1

C1   C2   C3
R1   1  2.0  3.0
R2   4  5.0  NaN
R3   6  NaN  NaN

In [ ]:
dFrame2=pd.DataFrame([[10,20],[30],[40,50]],columns=['C2','C5'],index=['R4','R2','R5'])

In [ ]:
dFrame2

C2    C5
R4  10  20.0
R2  30   NaN
R5  40  50.0

In [ ]:
dFrame1=dFrame1.append(dFrame2)

In [ ]:
dFrame1

C1    C2   C3    C5
R1  1.0   2.0  3.0   NaN
R2  4.0   5.0  NaN   NaN
R3  6.0   NaN  NaN   NaN
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0

In [ ]:
# another way
dFrame2=dFrame2.append(dFrame1,sort='True')
dFrame2

C1    C2   C3    C5
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0
R1  1.0   2.0  3.0   NaN
R2  4.0   5.0  NaN   NaN
R3  6.0   NaN  NaN   NaN
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0
R1  1.0   2.0  3.0   NaN
R2  4.0   5.0  NaN   NaN
R3  6.0   NaN  NaN   NaN
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0

In [ ]:
# another way
dFrame2=dFrame2.append(dFrame1,sort='False')
dFrame2

C1    C2   C3    C5
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0
R1  1.0   2.0  3.0   NaN
R2  4.0   5.0  NaN   NaN
R3  6.0   NaN  NaN   NaN
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0
R1  1.0   2.0  3.0   NaN
R2  4.0   5.0  NaN   NaN
R3  6.0   NaN  NaN   NaN
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0
R1  1.0   2.0  3.0   NaN
R2  4.0   5.0  NaN   NaN
R3  6.0   NaN  NaN   NaN
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0

In [ ]:
# Attribute of DataFrames
ForestArea={
    'Assam':pd.Series([78438,2797,10192,15116],index=['GeoArea','VeryDense','ModerateDense','OpenForest']),
    'Kerala':pd.Series([38852,1663,8407,9251],index=['GeoArea','VeryDense','ModerateDense','OpenForest']),
    'Delhi':pd.Series([1483,6.72,56.24,129.45],index=['GeoArea','VeryDense','ModerateDense','OpenForest'])
    }


In [ ]:
ForestAreaDF=pd.DataFrame(ForestArea)


In [ ]:
ForestAreaDF

Assam  Kerala    Delhi
GeoArea        78438   38852  1483.00
VeryDense       2797    1663     6.72
ModerateDense  10192    8407    56.24
OpenForest     15116    9251   129.45

In [ ]:
# some attributes of pandas dataframe
ForestAreaDF.index  # to display row lables

Index(['GeoArea', 'VeryDense', 'ModerateDense', 'OpenForest'], dtype='object')

In [ ]:
ForestAreaDF.columns # to display column lables

Index(['Assam', 'Kerala', 'Delhi'], dtype='object')

In [ ]:
ForestAreaDF.dtypes

Assam       int64
Kerala      int64
Delhi     float64
dtype: object

In [ ]:
ForestAreaDF.values

array([[7.8438e+04, 3.8852e+04, 1.4830e+03],
       [2.7970e+03, 1.6630e+03, 6.7200e+00],
       [1.0192e+04, 8.4070e+03, 5.6240e+01],
       [1.5116e+04, 9.2510e+03, 1.2945e+02]])

In [ ]:
ForestAreaDF.shape

(4, 3)

In [ ]:
ForestAreaDF.size # total values in the dataframe

12

In [ ]:
ForestAreaDF.T # transpose of the dataframe

GeoArea  VeryDense  ModerateDense  OpenForest
Assam   78438.0    2797.00       10192.00    15116.00
Kerala  38852.0    1663.00        8407.00     9251.00
Delhi    1483.0       6.72          56.24      129.45

In [ ]:
ForestAreaDF.head(2)

Assam  Kerala    Delhi
GeoArea    78438   38852  1483.00
VeryDense   2797    1663     6.72

In [ ]:
ForestAreaDF.tail(2)

Assam  Kerala   Delhi
ModerateDense  10192    8407   56.24
OpenForest     15116    9251  129.45

In [ ]:
ForestAreaDF.empty # if dataframe is empty it will return true otherwise false will be returned

False

#Importing and Exporting data between CSV files and DataFrames

In [ ]:
marks=pd.read_csv("ResultData.csv",sep=',',header=0)
# sep specify the values are separated by comma, semicolon,tab or any other
# by default value for sep a space

In [ ]:
marks

RollNo   Name  ECO  Maths
0       1   arun   18     20
1       2   kavi   50     58
2       3  priya   60     68
3       4   prem   89     78
4       5    ram   95     85

In [ ]:
marks1=pd.read_csv('ResultData.csv',sep=',',names=['RNo','StudentName','Sub1','Sub2'],header=0)
# excute with and without header =0 u can understand

In [ ]:
marks1

RNo StudentName  Sub1  Sub2
0    1        arun    18    20
1    2        kavi    50    58
2    3       priya    60    68
3    4        prem    89    78
4    5         ram    95    85

In [ ]:
# Exporting a DataFrame to a CSV file
ResultDF

NameError: ignored

In [ ]:
# check in our folder u can easily understand
ResultDF.to_csv('output_new.csv',sep=',')

NameError: ignored

In [ ]:
ResultDF.to_csv('output_new1.csv',sep='@',header=False,index=False)
# Check the output you can understand the important of sep and header and index
